"  ++++++++++++++++VundleVim-START++++++++++++++++
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'scrooloose/nerdtree'
" Bundle 'Lokaltog/vim-powerline'
Bundle 'vim-airline/vim-airline'
Bundle 'vim-airline/vim-airline-themes'
Bundle 'vim-scripts/bash-support.vim'
Bundle 'Yggdroot/indentLine'
Bundle 'fatih/vim-go'
Plugin 'marijnh/tern_for_vim'


" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"  ++++++++++++++++VundleVim-END++++++++++++++++




"  ++++++++++++++++VIM 文本编辑器相关配置+++++++++++++++++


" 设置制表符等于多少空格
"set ts=2 " 配置一个TAB占用多少个空格
"set softtabstop=2 " 每次退格将删除X个空格
"set shiftwidth=2 " 使用每层缩进的空格数
set autoindent
"set autoread  " 设置文件修改时自动reload
set syntax=on " 配置语法高亮
set ignorecase " 设置搜索时忽略大小写
set expandtab  " 配置使用空格代替空格
set tabstop=4  " 配置tab占用的空格数量
set number
set backspace=2 " 兼容mac 下vim的退格键配置
set pastetoggle=<F10> " 解决在xshell等终端中使用ctrl+v黏贴时格式错乱的问题
syntax enable
" let g:solarized_termcolors=256
set background=dark
colorscheme solarized
" 配置显示横竖定位符
set cursorcolumn
set cul
set encoding=utf-8


"  ++++++++++++++++VIM 插件的相关配置+++++++++++++++++
" 配置NEDTree的配置
let NERDTreeWinPos='left'
let NERDTreeWinSize=30
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map wm :NERDTreeToggle<CR>
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Tagbar配置
" nmap <F8> :TagbarToggle<CR>

" 有道词典配置
" vnoremap <silent> <C-T> :<C-u>Ydv<CR>
" nnoremap <silent> <C-T> :<C-u>Ydc<CR>
" noremap <leader>yd :<C-u>Yde<CR>
"
"

" Yggdroot/indentLine 显示渐进线的插件配置
" let g:indentLine_char='┆'
" let g:indentLine_enabled = 1

" YouCompleteMe插件配置
let g:ycm_seed_identifiers_with_syntax=1 " 开启基于语义的补全
let g:ycm_complete_in_strings = 1        " 在字符串收入中也能补全
let g:ycm_autoclose_preview_window_after_completion=1 " 补全后自动关机预览窗口
let g:ycm_python_binary_path = 'python'  " 解决在python的visual_env中多个不同版本存在时出现依赖库不提示的问题
set completeopt=menu,menuone " 解决YCM中自带的函数原型预览功能
let g:ycm_add_preview_to_completeopt = 0

" CTags 配置
" let Tlist_Use_Right_Window = 1



" vim-airline 配置
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'
let g:airline_theme='powerlineish'
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'



" 
autocmd BufNewFile,BufRead Makefile setlocal noexpandtab
autocmd BufNewFile,BufRead makefile setlocal noexpandtab
