# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

[[ -s "/home/ijarvis/.gvm/scripts/gvm" ]] && source "/home/ijarvis/.gvm/scripts/gvm"



export GOPATH=${HOME}/workspace/goworkspace
export PATH=$PATH:${GOPATH}/bin
export PATH=$PATH:${HOME}/.local/bin



if [ -f `which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /home/ijarvis/Tools/powerline/powerline/bindings/bash/powerline.sh
fi

#GIT_PROMPT_ONLY_IN_REPO=1
#source ~/.bash-git-prompt/gitprompt.sh

[ -s "/home/ijarvis/.jabba/jabba.sh" ] && source "/home/ijarvis/.jabba/jabba.sh"
